services: 
  db:
    container_name: postgres-spring-boot-full
    image: postgres:latest
    environment:
      POSTGRES_USER: expensetrackingdb
      POSTGRES_PASSWORD: password123
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - app-network
    restart: unless-stopped

  backend:
    container_name: spring-boot-backend-full
    build:
      context: ./expensetrackingbackend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/expensetrackingdb
      - SPRING_DATASOURCE_USERNAME=expensetrackingdb
      - SPRING_DATASOURCE_PASSWORD=password123
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    container_name: react-frontend-full
    build:
      context: ./expensetrackingfrontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db:

